
# log config
debug: true
trace: false
logging:
  level:
    root: info
    com.lazycece: DEBUG

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/reusable_admin?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

# mongo config
mongodb:
  mongo-default:
    host: 127.0.0.1
    port: 27017
    database: admindb
    username: admin
    password: admin123
  mongo-log:
    host: 127.0.0.1
    port: 27017
    database: admindb_log
    username: admin
    password: admin123

#upload file config
upload-file:
  file-path: /home/staticweb/reusable-admin/
  root-url:  http://127.0.0.1/staticweb/reusable-admin/
  inner-ip: 127.0.0.1
  outer-ip: 127.0.0.1
