

  -- @author lazycece
  -- all the db's table init sql as follow.

  CREATE TABLE IF NOT EXISTS admin_user (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '主键ID',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    status VARCHAR(8) NOT NULL COMMENT '数据状态',
    operator VARCHAR (255) COMMENT '操作者',
    username VARCHAR (255) NOT NULL COMMENT '用户名',
    password VARCHAR (32) NOT NULL COMMENT '密码',
    name VARCHAR (255) NOT NULL COMMENT '真实姓名',
    telephone VARCHAR (11) NOT NULL COMMENT '电话号码',
    email VARCHAR (255) COMMENT '邮箱',
    role_id bigint NOT NULL COMMENT '所属角色ID',
    PRIMARY KEY (id)
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;

  CREATE TABLE IF NOT EXISTS menu(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '主键ID',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    status VARCHAR(8) NOT NULL COMMENT '数据状态',
    operator VARCHAR (255) COMMENT '操作者',
    name VARCHAR(255) NOT NULL COMMENT '菜单名称',
    icon VARCHAR(255) NOT NULL COMMENT '图标',
    description VARCHAR(255) COMMENT '菜单描述',
    router VARCHAR(255) NOT NULL COMMENT '路由',
    parent_id BIGINT NOT NULL COMMENT '父级菜单ID',
    PRIMARY KEY (id)
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;

  CREATE TABLE IF NOT EXISTS permission(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '主键ID',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    status VARCHAR(8) NOT NULL COMMENT '数据状态',
    operator VARCHAR (255) COMMENT '操作者',
    name VARCHAR(255) NOT NULL COMMENT '资源名称',
    permission VARCHAR(255) NOT NULL COMMENT '资源权限',
    description VARCHAR(255) COMMENT '资源描述',
    menu_id BIGINT NOT NULL COMMENT '所属菜单ID',
    PRIMARY KEY (id)
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;

  CREATE TABLE IF NOT EXISTS admin_role(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '主键ID',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    status VARCHAR(8) NOT NULL COMMENT '数据状态',
    operator VARCHAR (255) COMMENT '操作者',
    name VARCHAR(255) NOT NULL COMMENT '角色名称',
    menu_set VARCHAR(512) NOT NULL COMMENT '菜单ID集合',
    permission_set VARCHAR(1024) NOT NULL COMMENT '资源权限集合',
    description VARCHAR(255) COMMENT '角色描述',
    PRIMARY KEY (id)
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;